import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const openSans = Open_Sans({
  weight: ["300", "700"],
  style: ["italic", "normal"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// bg-gradient-to-t from-blue-600 to-gray-900

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`min-h-screen bg-gradient-to-t from-blue-600 to-gray-900 ${openSans.className}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
